# Builds and publishes the documentation website
name: Build docs

on:
  workflow_dispatch:

concurrency:
  group: docs
  cancel-in-progress: true

permissions:
  # Both required by actions/deploy-pages
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: msbuild -t:restore src/Bonsai.PulsePal.sln

      - name: Build Solution
        run: msbuild src/Bonsai.PulsePal.sln /p:Configuration=Release

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Setup Bonsai
        working-directory: .bonsai
        run: .\Setup.ps1

      - name: Build Documentation
        working-directory: docs
        run: .\build.ps1

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
